blank_issues_enabled: true
contact_links:
  - name: Feature request
    url: https://github.com/orgs/fullpile/discussions/new?category=request-un-new-feature
    about: Request new feature
  - name: Ask a question, give feedback, share your project
    url: https://github.com/fullpile/frontpile/discussions
    about: Connect with other community members with GitHub discussions
  - name: Get help on Discord
    url: https://discord.gg/Mwh6XUa6
    about: Get help from maintainers on Discord
