name: "Build"

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
  push:
    branches:
      - "**"
      - "!main"

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v4
      - name: Use Node.js version
        uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"
          cache: "pnpm"
      - name: Install dependencies
        run: pnpm install
      - name: lint checks
        run: pnpm run lint
      - name: unit tests
        run: pnpm run test
      - name: build
        run: pnpm run build:all
